from django.conf import settings
from django.db import migrations,models
import django.db.models.deletion
class Migration(migrations.Migration):
    initial=True
    dependencies=[migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations=[
        migrations.CreateModel(name="Category",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120,unique=True)),("active",models.BooleanField(default=True))],options={"ordering":("name",)}),
        migrations.CreateModel(name="Subcategory",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("name",models.CharField(max_length=120)),("active",models.BooleanField(default=True)),("category",models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,related_name="subcategories",to="core.category"))],options={"ordering":("category__name","name",)}),
        migrations.AddConstraint(model_name="subcategory",constraint=models.UniqueConstraint(fields=("category","name"),name="unique_subcategory")),
        migrations.CreateModel(name="ServiceRequest",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("request_date",models.DateField()),("requester_type",models.CharField(blank=True,max_length=80)),("requester_reference",models.CharField(blank=True,db_index=True,max_length=100)),("requester_name",models.CharField(max_length=180)),("subject",models.CharField(max_length=240)),("resolution",models.TextField(blank=True)),("channel",models.CharField(choices=[("IN_PERSON","In person"),("EMAIL","Email"),("PHONE","Phone"),("CHAT","Chat"),("OTHER","Other")],default="IN_PERSON",max_length=20)),("status",models.CharField(choices=[("OPEN","Open"),("IN_PROGRESS","In progress"),("FORWARDED","Forwarded"),("RESOLVED","Resolved"),("CANCELLED","Cancelled")],default="OPEN",max_length=20)),("notes",models.TextField(blank=True)),("handled_by",models.CharField(max_length=160)),("import_key",models.CharField(blank=True,max_length=64,null=True,unique=True)),("created_at",models.DateTimeField(auto_now_add=True)),("updated_at",models.DateTimeField(auto_now=True)),("category",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="requests",to="core.category")),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,related_name="created_service_requests",to=settings.AUTH_USER_MODEL)),("subcategory",models.ForeignKey(blank=True,null=True,on_delete=django.db.models.deletion.PROTECT,related_name="requests",to="core.subcategory"))],options={"ordering":("-request_date","-id")}),
        migrations.CreateModel(name="ImportBatch",fields=[("id",models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name="ID")),("filename",models.CharField(max_length=255)),("dry_run",models.BooleanField(default=True)),("created_count",models.PositiveIntegerField(default=0)),("skipped_count",models.PositiveIntegerField(default=0)),("created_at",models.DateTimeField(auto_now_add=True)),("created_by",models.ForeignKey(on_delete=django.db.models.deletion.PROTECT,to=settings.AUTH_USER_MODEL))]),
    ]
