# Generated by Django 5.2.17 on 2026-09-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='channel',
            field=models.CharField(choices=[('IN_PERSON', 'Presencial'), ('EMAIL', 'Email'), ('PHONE', 'Telefone'), ('CHAT', 'Chat'), ('OTHER', 'Outro')], default='IN_PERSON', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('IN_PROGRESS', 'Em andamento'), ('FORWARDED', 'Encaminhado'), ('RESOLVED', 'Resolvido'), ('CANCELLED', 'Cancelado')], default='OPEN', max_length=20),
        ),
    ]
